### ISSUE TITLE
Logs aren't saved

### ISSUE THREAD

**Issue by mtliendo** [DevLifts/fit-cli#1]
Just making a note here in case others (or myself) want to jump on this. But I noticed that currently, when you save a log, it's not actually persisted anywhere.

### Proposed Idea

I think the simplest way is just to use the `fs` module and save to the users Desktop, but I'm just spit balling.

**Comment by jchiatt** [comment]
@mtliendo good catch! this isn't a thing yet because I basically just pushed up a very barebones version a few weeks ago that pretty much does nothing right now lol

The actual v1 will store locally and in our API

**Comment by jchiatt** [comment]
Gonna close this for now.
